services:
  vpn_alpha:
    restart: always
    build: .
    # cap_add и network_mode необходимы для работы sniffer (raw sockets)
    environment:
      - DEBUG=1
    networks:
      vpn_net:
        ipv4_address: 172.20.0.10

  vpn_beta:
    restart: always
    build: .
    environment:
      - DEBUG=1
    networks:
      vpn_net:
        ipv4_address: 172.20.0.11

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24