services:
  vpn_alpha:
    build: .
    # cap_add и network_mode необходимы для работы sniffer (raw sockets)
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      vpn_net:
        ipv4_address: 172.20.0.10

  vpn_beta:
    build: .
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      vpn_net:
        ipv4_address: 172.20.0.11

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24